server:
  port: 8087

spring:
  application:
    name: api-gateway   # Registered name in Eureka
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: subscriber-service
          uri: lb://subscriber-service
          predicates:
            - Path=/subscribers/**

        - id: plan-service
          uri: lb://plan-service
          predicates:
            - Path=/plans/**

        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
