server:
  port: 8081

spring:
  application:
    name: subscriber-service   # 👈 very important for Eureka + Gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/telecomdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
